import {
  BarChart3,
  BookOpen,
  Briefcase,
  Camera,
  Calendar,
  Code2,
  Cpu,
  Dumbbell,
  Folder,
  Globe,
  HeartPulse,
  Layers3,
  Leaf,
  Monitor,
  Mountain,
  Music,
  Palette,
  PiggyBank,
  Rocket,
  Stethoscope,
  Target,
  TrendingUp,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import {
  PROJECT_ICON_OPTIONS,
  type ProjectIcon,
} from "@/lib/projects/icons";

export const PROJECT_ICON_COMPONENTS: Record<ProjectIcon, LucideIcon> = {
  folder: Folder,
  music: Music,
  book: BookOpen,
  code: Code2,
  rocket: Rocket,
  chart: BarChart3,
  palette: Palette,
  camera: Camera,
  globe: Globe,
  calendar: Calendar,
  briefcase: Briefcase,
  target: Target,
  wrench: Wrench,
  layers: Layers3,
  zap: Zap,
  sport: Dumbbell,
  health: HeartPulse,
  medical: Stethoscope,
  cpu: Cpu,
  monitor: Monitor,
  economy: PiggyBank,
  trending: TrendingUp,
  nature: Leaf,
  mountain: Mountain,
};

export const PROJECT_ICON_ITEMS = PROJECT_ICON_OPTIONS.map((option) => ({
  ...option,
  Icon: PROJECT_ICON_COMPONENTS[option.value],
}));
